"""Core Stage Z operation: collapse one intermediate ``WeldJoint``.

See ``.claude/plans/comak-weld-collapse.md`` for the full design. In brief: the
placeholder sub-body is absorbed into the load-bearing main body by

  1. creating one ``PhysicalOffsetFrame`` on the main body at exactly the pose
     the sub-body occupied (a pure translation ``d`` -- welds are
     translation-only),
  2. retargeting every socket that pointed at the sub-body onto that frame,
  3. moving the sub-body's wrap objects + attached geometry onto that frame,
  4. folding the sub-body's mass + inertia into the main body (parallel axis),
  5. deleting the ``WeldJoint`` and the sub-body.

Because the offset frame sits at the old sub-body pose, no retargeted
component's local coordinates change -- the collapse is a pure structural
flattening, physically identical to the input.

Mutation strategy (important): ``collapse_weld`` performs only property edits
and calls ``finalizeFromProperties()`` -- never ``finalizeConnections()``.
``finalizeConnections`` resolves sockets and rebuilds the multibody tree, and
crashes if run on an intermediate (mid-surgery) model: stale transient
``PathWrapPoint`` components dangle, and a sub-body that is a weld *parent*
briefly leaves the main body with two inboard joints. The orchestrator therefore
calls ``finalizeConnections()`` exactly once, after every weld is collapsed and
the structure is final and valid.
"""

import numpy as np
import opensim as osim

from .inertia import combine_inertia

__all__ = ["collapse_weld"]


def _vec3(v):
    return osim.Vec3(float(v[0]), float(v[1]), float(v[2]))


def _np3(vec3: osim.Vec3) -> np.ndarray:
    return np.array([vec3.get(0), vec3.get(1), vec3.get(2)], dtype=float)


def _body_inertia_6vec(body: osim.Body) -> np.ndarray:
    """Return a body's inertia as ``(Ixx, Iyy, Izz, Ixy, Ixz, Iyz)``."""
    inertia = body.getInertia()
    moments = inertia.getMoments()
    products = inertia.getProducts()
    return np.array(
        [
            moments.get(0),
            moments.get(1),
            moments.get(2),
            products.get(0),
            products.get(1),
            products.get(2),
        ],
        dtype=float,
    )


def collapse_weld(
    model: osim.Model,
    weld_name: str,
    sub_name: str,
    main_name: str,
    d: np.ndarray,
) -> dict:
    """Collapse one intermediate ``WeldJoint`` in-place (property edits only).

    Parameters
    ----------
    model
        The model to mutate. Must be ``finalizeFromProperties()``-consistent on
        entry (a freshly loaded or just-collapsed model satisfies this).
    weld_name
        Name of the intermediate ``WeldJoint`` to collapse.
    sub_name, main_name
        Placeholder sub-body and load-bearing main body names, precomputed by
        the orchestrator (see ``topology.identify_sub_main``). Passed in rather
        than re-derived here because identifying them needs resolved
        connections, which ``collapse_weld`` deliberately does not maintain.
    d
        Sub-body-frame -> main-body-frame translation (3-vector), precomputed by
        the orchestrator from a single ``initSystem()``.

    Returns
    -------
    dict
        Per-weld report: sub/main names, ``d``, combined mass + mass center,
        and counts of retargeted sockets / moved wraps / moved geometry.

    Notes
    -----
    Does not call ``finalizeConnections()`` or ``printToXML`` -- the orchestrator
    owns those.
    """
    d = np.asarray(d, dtype=float)
    if d.shape != (3,):
        raise ValueError(f"d must be a 3-vector, got shape {d.shape}")

    body_set = model.getBodySet()
    sub = body_set.get(sub_name)
    main = body_set.get(main_name)
    sub_path = sub.getAbsolutePathString()

    # --- 3. create the offset frame on the main body -----------------------
    offset_name = f"{sub_name}_collapsed"
    offset = osim.PhysicalOffsetFrame()
    offset.setName(offset_name)
    offset.setParentFrame(main)
    offset.set_translation(_vec3(d))
    offset.set_orientation(osim.Vec3(0.0, 0.0, 0.0))
    main.addComponent(offset)
    model.finalizeFromProperties()
    offset_path = offset.getAbsolutePathString()

    # --- 4. retarget every socket whose connectee path is the sub-body -----
    # Compared as path strings: every reference to a placeholder sub-body in
    # the COMAK model is the absolute path '/bodyset/<sub>' (verified). The
    # weld being collapsed -- and its owned offset frames -- are skipped: they
    # are about to be deleted. Transient PathWrapPoints may also match; that is
    # harmless (they are regenerated by the final finalizeConnections).
    weld = model.getJointSet().get(weld_name)
    weld_path = weld.getAbsolutePathString()
    retarget_count = 0
    for comp in list(model.getComponentsList()):
        comp_path = comp.getAbsolutePathString()
        if comp_path == weld_path or comp_path.startswith(weld_path + "/"):
            continue
        for socket_name in list(comp.getSocketNames()):
            if comp.getSocket(socket_name).getConnecteePath() == sub_path:
                comp.updSocket(socket_name).setConnecteePath(offset_path)
                retarget_count += 1

    # --- 5. move attached geometry (visual meshes) onto the offset frame ---
    # append_attached_geometry deep-copies the value into the offset frame's
    # list property; pass the live reference (a Python-owned clone double-frees
    # and segfaults). Each Mesh's frame socket is '..', so on the offset frame
    # it resolves to the offset frame = the old sub-body pose.
    n_geometry = sub.getPropertyByName("attached_geometry").size()
    for i in range(n_geometry):
        offset.append_attached_geometry(sub.get_attached_geometry(i))

    # --- 5b. move wrap objects onto the offset frame -----------------------
    # WrapObjectSet is a property of PhysicalFrame, so a PhysicalOffsetFrame
    # hosts wraps just as a Body does. WrapObjects carry no socket -- their
    # placement is the frame-relative translation/xyz_body_rotation, unchanged
    # because the offset frame sits at the old sub-body pose. PathWrap entries
    # reference a wrap by bare name, so a moved-but-same-named wrap still
    # resolves with no PathWrap edit.
    sub_wraps = sub.getWrapObjectSet()
    moved_wraps = []
    for i in range(sub_wraps.getSize()):
        wrap = sub_wraps.get(i)
        moved_wraps.append(wrap.getName())
        offset.upd_WrapObjectSet().cloneAndAppend(wrap)

    # --- 6. fold sub-body mass + inertia into the main body ----------------
    combined_mass, combined_com, combined_inertia = combine_inertia(
        main.getMass(),
        _np3(main.getMassCenter()),
        _body_inertia_6vec(main),
        sub.getMass(),
        _np3(sub.getMassCenter()),
        _body_inertia_6vec(sub),
        d,
    )
    main.setMass(float(combined_mass))
    main.setMassCenter(_vec3(combined_com))
    main.setInertia(
        osim.Inertia(
            float(combined_inertia[0]),
            float(combined_inertia[1]),
            float(combined_inertia[2]),
            float(combined_inertia[3]),
            float(combined_inertia[4]),
            float(combined_inertia[5]),
        )
    )

    # --- 7. delete the WeldJoint, then the sub-body ------------------------
    joint_set = model.getJointSet()
    if not joint_set.remove(joint_set.getIndex(weld_name)):
        raise RuntimeError(f"failed to remove WeldJoint '{weld_name}' from JointSet")
    if not body_set.remove(body_set.getIndex(sub_name)):
        raise RuntimeError(f"failed to remove body '{sub_name}' from BodySet")

    # --- 8. rebuild property-derived caches (NOT connections) --------------
    model.finalizeFromProperties()

    return {
        "weld": weld_name,
        "sub_body": sub_name,
        "main_body": main_name,
        "offset_frame": offset_path,
        "d": d.tolist(),
        "combined_mass": float(combined_mass),
        "combined_mass_center": combined_com.tolist(),
        "n_sockets_retargeted": retarget_count,
        "n_wraps_moved": len(moved_wraps),
        "wraps_moved": moved_wraps,
        "n_attached_geometry_moved": int(n_geometry),
    }
